comment out bandd

diff --git a/scripts/two-chainz-band b/scripts/two-chainz-band
--- a/scripts/two-chainz-band
+++ b/scripts/two-chainz-band
@@ -13,10 +13,10 @@ RELAYER_DIR="$(dirname $SCRIPTDIR)"
 RELAYER_CONF="$HOME/.relayer"
 
 # Ensure bandd is installed
-if ! [ -x "$(which bandd)" ]; then
-  echo "Error: bandd is not installed." >&2
-  exit 1
-fi
+# if ! [ -x "$(which bandd)" ]; then
+#   echo "Error: bandd is not installed." >&2
+#   exit 1
+# fi
 
 # Ensure $consumer_cmd is installed
 if ! [ -x "$(which $consumer_cmd)" ]; then
